# Form implementation generated from reading ui file 'ventanasecundaria.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class VentanaSecundaria(QtWidgets.QWidget):
    def __init__(self, informacion):
        super().__init__()
        self.setupUi(self)
        self.mostrar_informacion(informacion)
        
    def setupUi(self, VentanaSecundaria):
        VentanaSecundaria.setObjectName("VentanaSecundaria")
        VentanaSecundaria.resize(668, 311)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=VentanaSecundaria)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(VentanaSecundaria)
        QtCore.QMetaObject.connectSlotsByName(VentanaSecundaria)

    def retranslateUi(self, VentanaSecundaria):
        _translate = QtCore.QCoreApplication.translate
        VentanaSecundaria.setWindowTitle(_translate("VentanaSecundaria", "VentanaSecundaria"))
        self.label.setText(_translate("VentanaSecundaria", "Información Mascota"))
        self.label_2.setText(_translate("VentanaSecundaria", "Datos de la mascota"))
        self.pushButton.setText(_translate("VentanaSecundaria", "OK"))

    def mostrar_informacion(self, informacion):
        self.label_2.setText(informacion)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    informacion = "Información de mascota"
    ventana_secundaria = VentanaSecundaria(informacion)
    ventana_secundaria.show()
    sys.exit(app.exec())
